language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean --config source/_data/next.yml
  - hexo g --config source/_data/next.yml

after_script:
  - cd ./public
  - git init
  - git config user.name "yzlnew"
  - git config user.email "yzlnew@gmail.com"
  - git add .
  - git commit -m "Site updated:"$(date +\ %y-%m-%d\ %H:%M:%S)
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog

env:
 global:
   - GH_REF: github.com/yzlnew/yzlnew.github.io.git
