---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Config
- type: directory
  path: content
  label: Posts
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo
  publish_command: hugo
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
