---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Config
  match: "**/*"
- type: directory
  path: content
  label: Posts
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo
  publish_command: hugo
  output_directory: public
version: '0.52'
